import os

class Config:
    """Base configuration class for Flask application."""

    # Secret key for session management and CSRF protection
    SECRET_KEY = os.environ.get('SECRET_KEY', 'you-will-never-guess')

    # Custom configuration options can be added here
    CUSTOM_SETTING = os.environ.get('CUSTOM_SETTING', 'default_value')

    # Example for debug mode (not for production)
    DEBUG = os.environ.get('FLASK_DEBUG', 'true') == 'true'


SWAN_DEFAULT_CONFIG = {
    "device_tag": "",
    "nb1_plmn": "",
    "nb1_bands": "3,8,20",
    "nb1_apn": "",
    "nb1_psm": 0,
    "nb1_psm_activetime": 0,
    "nb1_psm_tau": 0,
    "nb1_rai": 3,
    "nb1_apn_account_index": 0,
    "ntp_server": "0.europe.pool.ntp.org",
    "ntp_port": 123,
    "ntp_auto_sync": 0,
    "timezone": 4,
    "daylightsaving_enable": 1,
    "upload_server": "weptech-iot.de/swan2",
    "upload_remote_port": 31031,
    "upload_local_port": 28028,
    "upload_proto": 3,
    "upload_method": 1,
    "upload_account_index": 0,
    "upload_format": 2,
    "upload_format_spec_1": 0xFFFFFFFF,
    "upload_format_spec_2": 0xFFFFFFFF,
    "upload_format_spec_3": 0xFFFFFFFF,
    "upload_retries": 2,
    "upload_months": 4095,
    "upload_days": 16385,
    "upload_weeks": 0,
    "upload_week_days": 0,
    "upload_start_hour": 0,
    "upload_start_minute": 0,
    "upload_hours": 0,
    "upload_per_hour": 1,
    "upload_jitter": 0,
    "lwm2m_idle_time": 120,
    "lwm2m_notify_with_ack": 1,
    "lwm2m_notify_retry_cnt": 2,
    "lwm2m_notify_timeout": 7,
    "lwm2m_lifetime": 150,
    "collect_mode": 8,
    "collect_rssi_min": -108,
    "collect_rssi_max": 127,
    "collect_use_dll": 0,
    "collect_max_num_meters": 5,
    "collect_duration": 300,
    "collect_flags": 0,
    "collect_datalog_flags": 3,
    "collect_months": 4095,
    "collect_days": 16385,
    "collect_weeks": 0,
    "collect_week_days": 0,
    "collect_start_hour": 0,
    "collect_start_minute": 0,
    "collect_hours": 0,
    "collect_per_hour": 1,
    "collect_jitter": 0,
    "upload_after_collect": 0,
    "collect_mode_2": 0,
    "collect_rssi_min_2": -108,
    "collect_rssi_max_2": 127,
    "collect_use_dll_2": 0,
    "collect_max_num_meters_2": 5,
    "collect_duration_2": 300,
    "collect_flags_2": 0,
    "collect_datalog_flags_2": 3,
    "collect_months_2": 0,
    "collect_days_2": 0,
    "collect_weeks_2": 0,
    "collect_week_days_2": 0,
    "collect_start_hour_2": 0,
    "collect_start_minute_2": 0,
    "collect_hours_2": 0,
    "collect_per_hour_2": 1,
    "collect_jitter_2": 0,
    "upload_after_collect_2": 0,
    "quietmode": 0,
    "nfc_fast_install": 1,
    "uart_sci": 0,
    "ci_field_blacklist": 0,
    "autostart": 0,
    "clear_status_after_ul": 1,
    "prefilter_devicetype": "",
    "prefilter_manufacturer": "",
    "sync_rx": 1,
    "sync_rx_duration": 2000,
    "sync_rx_interval": 300,
    "sync_rx_storage": 3600,
    "sync_rx_max_time_gap": 3600,
    "sync_rx_meter": "12345678-WEP-02-02",
    "upload_alarm_mask": 0,
    "upload_alarm_interval": 80,
}